export const FETCH_POST = 'FETCH_POST'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POSTS = 'UPDATE_POSTS'
export const LIKE_POSTS = 'LIKE_POSTS'
export const DELETE_POSTS = 'DELETE_POSTS'